name: Build

on:
  pull_request:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install marp-cli
        shell: pwsh
        run: |
          $version = "4.3.1"
          $url = "https://github.com/marp-team/marp-cli/releases/download/v${version}/marp-cli-v${version}-win.zip"
          Invoke-WebRequest -Uri $url -OutFile marp-cli.zip
          Expand-Archive -Path marp-cli.zip -DestinationPath marp-cli
          "marp-cli" | Out-File -FilePath $env:GITHUB_PATH -Append -Encoding utf8

      - name: Export all decks
        shell: pwsh
        run: .\build.ps1 -Bootstrap

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: summit-2026-decks
          path: dist\*
